export const PROJECT_NAME_RANGE = "A1:D4";

export const PROJECT_NAME_RANGE_FILL_COLOR = "#1364BB";

export const PROJECT_NAME_RANGE_FONT_COLOR = "white";

export const PROJECT_NAME_CELL_INDEX = "B2";

export const PROJECT_HEADER_RANGE = "A1:D3";

export const PROJECT_KICKOFF_DATE_CELL_INDEX = "B3";

export const PROJECT_KICKOFF_DATE_RANGE = "B3:B4";

export const PROJECT_COLUMN_HEADER_RANGE = "C3:D4";

export const PROJECT_COLUMN_HEADER_RANGE_FILL_COLOR = "white";

export const PROJECT_COLUMN_HEADER_RANGE_FONT_COLOR = "black";

export const PROJECT_CALENDAR_MONTH_START_INDEX_INCLUSIVE = "E1";

export const PROJECT_CALENDAR_CELL_COLUMN_WIDTH = 26;

export const PROJECT_CALENDAR_MONTH_CALENDAR_FILL_COLOR_DARK = "#8FBFF3";

export const PROJECT_CALENDAR_MONTH_CALENDAR_FILL_COLOR_LIGHT = "#C7DFFA";

export const PROJECT_SHORT_DATE_FORMAT = "mmmm yyyy";

export const PROJECT_SATURDAY_CALENDAR_CELL_FILL_COLOR = "#E6B8AF";

export const PROJECT_SUNDAY_CALENDAR_CELL_FILL_COLOR = "#DD7E6B";
